export enum GenresMusic {
  Pop = "Pop",
  HipHop = "HipHop",
  Rock = "Rock",
  RhythmAndBlues = "RhythmAndBlues",
  Soul = "Soul",
  Reggae = "Reggae",
  Country = "Country",
  Funk = "Funk",
  Folk = "Folk",
  MiddleEastern = "MiddleEastern",
  Jazz = "Jazz",
  Disco = "Disco",
  Classical = "Classical",
  Electronic = "Electronic",
  Blues = "Blues",
  Vocal = "Vocal",
  Christian = "Christian",
  Traditional = "Traditional",
}
